language: node_js
node_js:
 - 6

install:
 - npm install --production
 - npm install browserify uglifyify jest

before_deploy:
 - npm run build

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
